Repository koreader/koreader-base, pull requests merged in 2019-04, with the labels that each got.

#892 Fix MuPDF vendoring
  Makefile.defs
  Makefile.third
  thirdparty/libjpeg-turbo/CMakeLists.txt
  thirdparty/lua-serialize/CMakeLists.txt
  thirdparty/lua-serialize/lua-serialize-lto.patch
  thirdparty/luajit/CMakeLists.txt
  thirdparty/luajit/koreader-luajit-makefile-tweaks.patch
  thirdparty/luasec/CMakeLists.txt
  thirdparty/luasocket/CMakeLists.txt
  thirdparty/mupdf/CMakeLists.txt
Labels: bug

#894 [fix, Android] Versioned OpenSSL libs
  Makefile.defs
Labels: bug

#895 [fix, build] Don't fail quietly on patching failure
  thirdparty/cmake_modules/koreader_thirdparty_common.cmake
  thirdparty/cmake_modules/patch-wrapper.sh
  thirdparty/czmq/CMakeLists.txt
  thirdparty/djvulibre/CMakeLists.txt
  thirdparty/dropbear/CMakeLists.txt
  thirdparty/glib/CMakeLists.txt
  thirdparty/lua-serialize/CMakeLists.txt
  thirdparty/luajit/CMakeLists.txt
  thirdparty/mupdf/CMakeLists.txt
  thirdparty/openssh/CMakeLists.txt
  thirdparty/openssl/CMakeLists.txt
  thirdparty/sdcv/CMakeLists.txt
  thirdparty/tar/CMakeLists.txt
  thirdparty/zsync/CMakeLists.txt
Labels: bug

#898 Re-enforce silent builds for iconv & gettext
  thirdparty/gettext/CMakeLists.txt
  thirdparty/libiconv/CMakeLists.txt
Labels: Android

#897 [fix] Detect Clang
  .ci/before_install.sh
  .circleci/config.yml
  .travis.yml
  Makefile.defs
  README.md
Labels: bug

#900 [fix] ffi/SDL2: crash with `SDL_FULLSCREEN`
  ffi/SDL2_0.lua
Labels: bug

#901 fix incorrect merge with master from #843
  ffi/framebuffer.lua
  spec/unit/framebuffer_spec.lua
Labels: bug

#909 Pass arbitrary DjVu text annotations to frontend
  djvu.c
Labels: enhancement
